### ISSUE TITLE
A starter on creating the actor

### ISSUE THREAD

**Issue by pwatson100** [nfoxsc/fvtt-alien-character-generator#1]
Hi,    Really nice macro.  In the code below I have added (at the end) a start on creating the actor.  The trickiest bit is the Career as it is stored as a numeric value so I had to add a new item to the careerList array (menuItemNumber).

Hope this helps you on your way.  

Paul. 

[create-actor.txt](https://github.com/nfoxsc/fvtt-alien-character-generator/files/11078011/create-actor.txt)

**Comment by nfoxsc** [comment]
Completed.

**Comment by nfoxsc** [comment]
completed
